### ISSUE TITLE
Get Statistics

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#5] opened 2017-03-13 13:06 UTC
Do that after: #4

Get Statistics
- number of languages
- pagecount (how many pages exist in that particular wiki?)
     - todo: what is the difference between articles and pages (somehow used interchangeably)
- categories 
     - main category called "hubs": Videogames, Entertainment or Lifestyle
     - topics

**Comment by AlexandraHofmann** [comment] 2017-03-17 13:18
duplicate of #8 
therefore closed

**Closed as completed by AlexandraHofmann** 2017-03-17 13:18 UTC
Labels: duplicate, poc
