### ISSUE TITLE
Write Analyzer for Data File

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#8] opened 2017-03-16 19:58 UTC
The data is downloaded, the next step is to create meaningful statistics.
A Java program might be suitable for this. Excel might also work.

Minimal Scope
- How many wikis do we have?
- How many pages do we have?
- What is the distribution of topics?
- What is the distribution of languages? (Attention: also use domains to determine language as the language property is not always filled)

**Comment by AlexandraHofmann** [comment] 2017-03-17 13:17
duplicate of #5

**Closed as completed** 2017-03-20 12:48 UTC
Labels: poc
